[project]
name = "transactions-eda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
    "streamlit>=1.50.0",
    "plotly>=5.22.0",
    "scipy>=1.16.3",
]
